# Generated by Django 5.2.6 on 2025-10-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='voter_id_number',
            field=models.CharField(),
        ),
    ]
