# Generated by Django 5.2.6 on 2025-10-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0002_alter_voter_voter_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='address_apt_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='address_street_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
