# Generated by Django 5.2.6 on 2025-10-29 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0003_alter_voter_address_apt_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='voter_id_number',
        ),
        migrations.AlterField(
            model_name='voter',
            name='address_apt_number',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='address_street_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='address_street_number',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='address_zip_code',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='date_of_registration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='first_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='last_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='party_affiliation',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='voter',
            name='precinct_number',
            field=models.CharField(),
        ),
    ]
